// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU4teQLheC-O1cD1PdrZzyB6liDDI7_7M',
    appId: '1:1010703168805:web:9c4b693c7993d66e24d6cc',
    messagingSenderId: '1010703168805',
    projectId: 'head-first-dd93f',
    authDomain: 'head-first-dd93f.firebaseapp.com',
    storageBucket: 'head-first-dd93f.appspot.com',
    measurementId: 'G-MKJ4WQ51WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYF475S07aVKZyRFlSwOD_pdsHFmpa0sg',
    appId: '1:1010703168805:android:df0ecec3ca4f45e024d6cc',
    messagingSenderId: '1010703168805',
    projectId: 'head-first-dd93f',
    storageBucket: 'head-first-dd93f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPaw2SAgoCzNswbumLH5PLZwxAakdxD1I',
    appId: '1:1010703168805:ios:f66b3ee6c4ed934324d6cc',
    messagingSenderId: '1010703168805',
    projectId: 'head-first-dd93f',
    storageBucket: 'head-first-dd93f.appspot.com',
    iosBundleId: 'com.example.arVisionaryExplora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPaw2SAgoCzNswbumLH5PLZwxAakdxD1I',
    appId: '1:1010703168805:ios:685ca9a97bd0870224d6cc',
    messagingSenderId: '1010703168805',
    projectId: 'head-first-dd93f',
    storageBucket: 'head-first-dd93f.appspot.com',
    iosBundleId: 'com.example.arVisionaryExplora.RunnerTests',
  );
}
